"use client";

import React, { useState, useEffect } from "react";
import { getReports, generateReport } from "@/lib/api/reports";
import type { Report } from "@/lib/types";
import { Button } from "@/components/ui/Button";
import { ErrorState, EmptyState } from "@/components/ui/EmptyState";
import { Skeleton } from "@/components/ui/Skeleton";
import { Modal } from "@/components/ui/Modal";
import { Input } from "@/components/ui/Input";
import { toast } from "sonner";
import { FileText, Download, Eye, Plus, Calendar } from "lucide-react";
import { formatDate } from "@/lib/helpers";

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [createOpen, setCreateOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [form, setForm] = useState({ dateFrom: "", dateTo: "" });

  const fetchReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getReports();
      setReports(data);
    } catch (err: any) {
      setError(err.message || "Failed to load reports");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.dateFrom || !form.dateTo) {
      toast.error("Please select a date range");
      return;
    }
    setGenerating(true);
    try {
      await generateReport(form);
      toast.success("Report generated successfully");
      setCreateOpen(false);
      fetchReports();
    } catch (err: any) {
      toast.error(err.message || "Failed to generate report");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="page-title">Voice of Customer Reports</h1>
          <p className="page-subtitle">Generate and view automated executive summaries</p>
        </div>
        <Button onClick={() => setCreateOpen(true)} leftIcon={<Plus className="h-4 w-4" />}>
          Generate Report
        </Button>
      </div>

      {error && !loading ? (
        <ErrorState description={error} onRetry={fetchReports} />
      ) : loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="card p-5">
              <Skeleton className="h-5 w-3/4 mb-2" />
              <Skeleton className="h-4 w-1/2 mb-6" />
              <Skeleton className="h-10 w-full" />
            </div>
          ))}
        </div>
      ) : reports.length === 0 ? (
        <EmptyState 
          title="No reports generated" 
          description="Create your first Voice of Customer report to share insights with your team."
          action={{ label: "Generate Report", onClick: () => setCreateOpen(true) }}
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reports.map((report) => (
            <div key={report.id} className="card flex flex-col hover:border-brand-300 transition-colors">
              <div className="p-5 flex-1">
                <div className="flex items-start justify-between mb-3">
                  <div className="w-10 h-10 bg-brand-50 rounded-xl flex items-center justify-center text-brand-600 shrink-0">
                    <FileText className="h-5 w-5" />
                  </div>
                  <span className="text-[10px] font-medium px-2 py-1 bg-success-50 text-success-700 rounded-full">
                    {report.status}
                  </span>
                </div>
                <h3 className="text-base font-semibold text-neutral-900 mb-1">{report.title}</h3>
                <p className="text-sm text-neutral-500 mb-4 flex items-center gap-1.5">
                  <Calendar className="h-3.5 w-3.5" /> {report.period}
                </p>
                <div className="text-xs text-neutral-400">
                  <p>Generated by {report.generatedBy}</p>
                  <p>{formatDate(report.createdAt)}</p>
                </div>
              </div>
              <div className="p-3 border-t border-neutral-100 flex gap-2">
                <Button variant="secondary" size="sm" className="flex-1" leftIcon={<Eye className="h-3.5 w-3.5" />}>
                  View
                </Button>
                <Button variant="outline" size="sm" className="flex-1" leftIcon={<Download className="h-3.5 w-3.5" />}>
                  Export PDF
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}

      <Modal
        isOpen={createOpen}
        onClose={() => setCreateOpen(false)}
        title="Generate Report"
        description="Select a date range to generate an automated Voice of Customer summary."
        size="sm"
        footer={
          <>
            <Button variant="ghost" onClick={() => setCreateOpen(false)} disabled={generating}>
              Cancel
            </Button>
            <Button onClick={handleGenerate} loading={generating}>
              Generate
            </Button>
          </>
        }
      >
        <form onSubmit={handleGenerate} className="space-y-4">
          <Input
            type="date"
            label="From Date"
            value={form.dateFrom}
            onChange={(e) => setForm((f) => ({ ...f, dateFrom: e.target.value }))}
            required
          />
          <Input
            type="date"
            label="To Date"
            value={form.dateTo}
            onChange={(e) => setForm((f) => ({ ...f, dateTo: e.target.value }))}
            required
          />
        </form>
      </Modal>
    </div>
  );
}
