"use client";

import React, { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Printer, Calendar, Quote, Lightbulb } from "lucide-react";
import { getReportById } from "@/lib/api/reports";
import type { Report } from "@/lib/types";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Skeleton";
import { ErrorState } from "@/components/ui/EmptyState";
import { usePermissions } from "@/hooks/usePermissions";
import { formatDate } from "@/lib/helpers";

export default function ReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const perms = usePermissions();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setReport(await getReportById(id));
    } catch (err: any) {
      setError(err.message || "Failed to load report");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    load();
  }, [load]);

  // "Export PDF" opens this page with ?print=1 → open the browser's
  // print dialog (choose "Save as PDF") once the report has rendered.
  useEffect(() => {
    if (
      report &&
      new URLSearchParams(window.location.search).get("print") === "1"
    ) {
      const t = setTimeout(() => window.print(), 400);
      return () => clearTimeout(t);
    }
  }, [report]);

  if (loading) {
    return (
      <div className="max-w-3xl space-y-4">
        <Skeleton className="h-8 w-2/3" />
        <Skeleton className="h-4 w-1/3" />
        <Skeleton className="h-40 w-full" />
      </div>
    );
  }

  if (error || !report) {
    return <ErrorState description={error ?? "Report not found"} onRetry={load} />;
  }

  const sentiment = report.sentimentShift;
  const maxThemeCount = Math.max(1, ...(report.topThemes ?? []).map((t) => t.count));

  return (
    <div className="max-w-3xl space-y-4 animate-fade-in">
      <div className="flex items-center justify-between print:hidden">
        <Button
          variant="ghost"
          size="sm"
          leftIcon={<ArrowLeft className="h-4 w-4" />}
          onClick={() => router.push("/reports")}
        >
          Back to reports
        </Button>
        {perms.canExportData && (
          <Button
            variant="outline"
            size="sm"
            leftIcon={<Printer className="h-4 w-4" />}
            onClick={() => window.print()}
          >
            Save as PDF
          </Button>
        )}
      </div>

      <article className="card p-6 md:p-8 space-y-8 print:shadow-none print:border-0 [print-color-adjust:exact] [-webkit-print-color-adjust:exact]">
        <header>
          <p className="text-xs font-semibold tracking-wide text-brand-600 uppercase mb-1">
            LOOP · Voice of Customer
          </p>
          <h1 className="text-2xl font-bold text-neutral-900">{report.title}</h1>
          <p className="text-sm text-neutral-500 mt-2 flex items-center gap-1.5">
            <Calendar className="h-3.5 w-3.5" /> {report.period}
          </p>
          <p className="text-xs text-neutral-400 mt-1">
            Generated by {report.generatedBy} · {formatDate(report.createdAt)}
          </p>
        </header>

        {report.summary && (
          <section>
            <h2 className="text-sm font-semibold text-neutral-900 mb-2">Executive summary</h2>
            <p className="text-sm text-neutral-700 leading-relaxed">{report.summary}</p>
          </section>
        )}

        {sentiment && (
          <section>
            <h2 className="text-sm font-semibold text-neutral-900 mb-3">Sentiment</h2>
            <div className="space-y-2">
              {(
                [
                  ["Positive", sentiment.positive, "bg-success-500"],
                  ["Neutral", sentiment.neutral, "bg-neutral-400"],
                  ["Negative", sentiment.negative, "bg-danger-500"],
                ] as const
              ).map(([label, value, color]) => (
                <div key={label} className="flex items-center gap-3 text-sm">
                  <span className="w-16 text-neutral-600">{label}</span>
                  <div className="flex-1 h-2.5 bg-neutral-100 rounded-full overflow-hidden">
                    <div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} />
                  </div>
                  <span className="w-10 text-right font-medium text-neutral-800">{value}%</span>
                </div>
              ))}
            </div>
          </section>
        )}

        {report.topThemes && report.topThemes.length > 0 && (
          <section>
            <h2 className="text-sm font-semibold text-neutral-900 mb-3">Top themes</h2>
            <div className="space-y-2">
              {report.topThemes.map((t) => (
                <div key={t.theme} className="flex items-center gap-3 text-sm">
                  <span className="w-44 truncate text-neutral-700">{t.theme}</span>
                  <div className="flex-1 h-2.5 bg-neutral-100 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full bg-brand-500"
                      style={{ width: `${(t.count / maxThemeCount) * 100}%` }}
                    />
                  </div>
                  <span className="w-8 text-right font-medium text-neutral-800">{t.count}</span>
                </div>
              ))}
            </div>
          </section>
        )}

        {report.quotes && report.quotes.length > 0 && (
          <section>
            <h2 className="text-sm font-semibold text-neutral-900 mb-3 flex items-center gap-1.5">
              <Quote className="h-4 w-4 text-neutral-400" /> Notable quotes
            </h2>
            <div className="space-y-2">
              {report.quotes.map((q, i) => (
                <blockquote
                  key={i}
                  className="border-l-2 border-brand-200 pl-3 text-sm text-neutral-700 italic"
                >
                  “{q}”
                </blockquote>
              ))}
            </div>
          </section>
        )}

        {report.recommendations && report.recommendations.length > 0 && (
          <section>
            <h2 className="text-sm font-semibold text-neutral-900 mb-3 flex items-center gap-1.5">
              <Lightbulb className="h-4 w-4 text-neutral-400" /> Recommended actions
            </h2>
            <ol className="list-decimal pl-5 space-y-1.5 text-sm text-neutral-700">
              {report.recommendations.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ol>
          </section>
        )}
      </article>
    </div>
  );
}